pub mod catalog;
pub(crate) mod command;
pub mod config;
pub mod crypto;
pub mod document;
pub mod error;
pub mod fragment;
pub mod ingest;
pub mod install;
pub mod mcp;
pub mod merge;
pub mod read;
pub mod remote;
pub mod repo_id;
mod search_cache;
pub mod sessions;
pub mod sources;
pub mod store;
pub mod update;

pub use error::{Error, Result};
